steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY=${_VITE_GEMINI_API_KEY}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/voicepal'
      - '.'
  
  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/voicepal'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/voicepal'

# Substitutions (can be overridden from command line or set as defaults)
substitutions:
  _VITE_GEMINI_API_KEY: 'your-api-key-here'

options:
  logging: CLOUD_LOGGING_ONLY
